<script>
    import {fly} from "svelte/transition";
    import {Button, Row, Col} from 'sveltestrap';
    import {helloWorld} from '../stores/helloworld-store'
    import {getHelloWorld} from "../services/backend";
    import {onMount} from "svelte";

    let visible = false;

    let sayHello = () => {
        getHelloWorld()
                .then(e => {
                    $helloWorld = e.status
                })
    };

    let removeHello = () => {
        $helloWorld = undefined
    };

    onMount(() => {
        visible = true
    })
</script>


{#if visible}
    <Row class="my-5 text-justify">
        <Col sm={{ size: 8, offset: 2 }}>
            <h1 in:fly="{{ y: 200, duration: 1000 }}" class="display-3">Hello Svelte + Express!</h1>
            <p in:fly="{{ y: 200, duration: 1000, delay: 100 }}">
                Welcome to your new Svelte + Express app! Some default components, stores, services are provided to help
                you
                starting.
            </p>
            <hr in:fly="{{ y: 200, duration: 1000, delay: 200 }}" class="my-2"/>
            <p in:fly="{{ y: 200, duration: 1000, delay: 300 }}" >
                All Svelte components are located in the client folder whereas all Express functions are in the server
                folder.
            </p>
            <h3 in:fly="{{ y: 200, duration: 1000, delay: 400 }}" >Client</h3>
            <p in:fly="{{ y: 200, duration: 1000, delay: 500 }}" >
                Sveltstrap and Recto (Bootstrap fork) are provided to help you start a responsive application. But you
                can
                of course change these libraries to use whatever you want to use.<br/>

                For routing, svelte-routing is used. All routes are located in App component. Pages are located in the
                pages
                folder.<br/>

                Backend calls are located in services folder, and plain old fetch API is used.
            </p>
            <h3 in:fly="{{ y: 200, duration: 1000, delay: 600 }}" >Server</h3>
            <p in:fly="{{ y: 200, duration: 1000, delay: 700 }}" >
                Express is used to provide a REST API. CORS, Body Parser (json), error handlers are configured in
                app.mjs
                file.<br/>
                This server is also used to serve the frontend app, which is generated by Rollup in public folder as
                static
                files.
            </p>
            <p in:fly="{{ y: 200, duration: 1000, delay: 800 }}" >
                The button bellow will trigger a call to the backend server to say hello. Try it!
            </p>
            <p in:fly="{{ y: 200, duration: 1000, delay: 900 }}"  class="lead">
                <Button class="btn-pill" color="primary" on:click={sayHello}>Say hello</Button>
                <Button class="btn-pill" color="secondary" on:click={removeHello}>Say goodbye</Button>
            </p>
        </Col>
    </Row>
{/if}